### ISSUE TITLE
The code does not have the files uploaded correctly

### ISSUE THREAD

**Issue by Aitooor** [KarmaConfigs/ClosedBlocksElevator#2]
I can't copile it, becouse class is missing

<img width="1209" alt="Captura de pantalla 2023-11-25 a las 0 20 54" src="https://github.com/KarmaDeb/ClosedBlocksElevator/assets/80640002/6cfb4305-9652-4281-b30d-c2a435b801d2">

**Comment by Aitooor** [comment]
Will it possible to update it?

**Comment by KarmaDeb** [comment]
> Will it possible to update it?

I will update the source code asp

**Comment by Aitooor** [comment]
> > Will it possible to update it?
> 
> 
> 
> I will update the source code asp

Thanks🙏

**Comment by Aitooor** [comment]
Will it posible to update it?

**Comment by KarmaDeb** [comment]
Fixed under commit b272b2cf60e68a8db8a514e6de444db7c458171d

Sorry for taking this long :(

**Comment by KarmaDeb** [comment]
The plugin is currently very messed up and a re-work is on-going
You can still modify the source code if you want, but a new refactorized version is coming out soon
